import type { NotificationRecord } from "@/features/notifications/types";

export const notificationsPreviewData: NotificationRecord[] = [
  {
    id: "campus-milestone-review",
    kind: "milestones",
    group: "today",
    artwork: "campus",
    title: "A milestone is ready for review",
    message:
      "CampusKonekt submitted proof for “Pilot with 3 campuses.” Review closes in 4 days.",
    timeLabel: "18 min ago",
    occurredAt: "2026-09-18T08:42:00.000Z",
    actionLabel: "Review milestone",
    actionHref: "/ideas",
    isRead: false,
  },
  {
    id: "sungrid-funded",
    kind: "campaigns",
    group: "today",
    artwork: "energy",
    title: "Campaign funded successfully",
    message:
      "SunGrid Community Power reached its funding target and is moving into delivery.",
    timeLabel: "2 hours ago",
    occurredAt: "2026-09-18T07:00:00.000Z",
    actionLabel: "View campaign",
    actionHref: "/ideas",
    isRead: false,
  },
  {
    id: "farmlink-review-closing",
    kind: "milestones",
    group: "today",
    artwork: "food",
    title: "Milestone review closes soon",
    message:
      "The current review window closes in 48 hours. Check the submitted evidence if you want to raise an objection.",
    timeLabel: "5 hours ago",
    occurredAt: "2026-09-18T04:00:00.000Z",
    actionLabel: "View proof",
    actionHref: "/ideas",
    isRead: false,
  },
  {
    id: "campus-milestone-approved",
    kind: "milestones",
    group: "this-week",
    artwork: "campus",
    title: "Milestone approved",
    message:
      "The prototype milestone was approved and the campaign is moving to the next delivery stage.",
    timeLabel: "Yesterday",
    occurredAt: "2026-09-17T12:00:00.000Z",
    actionLabel: "See progress",
    actionHref: "/ideas",
    isRead: true,
  },
  {
    id: "refund-available",
    kind: "refunds",
    group: "this-week",
    artwork: "refund",
    title: "A refund is available",
    message:
      "This campaign did not complete successfully. Eligible remaining funds are available to claim.",
    timeLabel: "Yesterday",
    occurredAt: "2026-09-17T08:00:00.000Z",
    actionLabel: "View refund",
    actionHref: "/ideas",
    isRead: true,
  },
  {
    id: "sungrid-creator-update",
    kind: "campaigns",
    group: "this-week",
    artwork: "energy",
    title: "Creator posted an update",
    message: "Amaka shared a new progress update with backers.",
    timeLabel: "3 days ago",
    occurredAt: "2026-09-15T13:00:00.000Z",
    actionLabel: "Read update",
    actionHref: "/ideas",
    isRead: true,
  },
  {
    id: "farmlink-following",
    kind: "campaigns",
    group: "older",
    artwork: "food",
    title: "You’re now following this project",
    message: "You’ll see future milestone, campaign, and creator updates here.",
    timeLabel: "1 week ago",
    occurredAt: "2026-09-11T10:00:00.000Z",
    actionLabel: "View project",
    actionHref: "/ideas",
    isRead: true,
  },
];
