import type { HomeDashboardData, IdeaSummary } from "@/features/home/types";

export const previewIdeas = {
  campusKonekt: {
    id: "campus-konekt",
    artwork: "campus",
    category: "Campus technology",
    creator: "Tobi Adeyemi",
    creatorInitials: "TA",
    description:
      "A student marketplace helping campus businesses reach the people already around them.",
    discoveryCategory: "technology",
    prePledged: { atomic: "840000000", currency: "NGN", decimals: 2 },
    supporters: 412,
    title: "CampusKonekt",
    validationPercent: 73,
  },
  sunGrid: {
    id: "sungrid-community-power",
    artwork: "energy",
    category: "Clean energy",
    creator: "Amaka Nwosu",
    creatorInitials: "AN",
    description:
      "Shared solar infrastructure for small businesses in communities with unreliable power.",
    discoveryCategory: "clean-energy",
    prePledged: { atomic: "1210000000", currency: "NGN", decimals: 2 },
    supporters: 286,
    title: "SunGrid Community Power",
    validationPercent: 61,
  },
  farmLink: {
    id: "farmlink-coldbox",
    artwork: "food",
    category: "Agriculture",
    creator: "Ibrahim Musa",
    creatorInitials: "IM",
    description:
      "Affordable cold storage helping small-scale farmers reduce post-harvest losses.",
    discoveryCategory: "agriculture",
    prePledged: { atomic: "670000000", currency: "NGN", decimals: 2 },
    supporters: 193,
    title: "FarmLink ColdBox",
    validationPercent: 48,
  },
  studyMate: {
    id: "studymate-ng",
    artwork: "community",
    category: "Education technology",
    creator: "Zainab Bello",
    creatorInitials: "ZB",
    description:
      "An AI study companion helping Nigerian students learn smarter and faster.",
    discoveryCategory: "technology",
    prePledged: { atomic: "280000000", currency: "NGN", decimals: 2 },
    supporters: 112,
    title: "StudyMate NG",
    validationPercent: 67,
  },
  naijaCraft: {
    id: "naijacraft-collective",
    artwork: "creative",
    category: "Creative",
    creator: "Adaeze Obi",
    creatorInitials: "AO",
    description:
      "A digital marketplace for Nigerian artisans and handmade goods.",
    discoveryCategory: "creative",
    prePledged: { atomic: "190000000", currency: "NGN", decimals: 2 },
    supporters: 98,
    title: "NaijaCraft Collective",
    validationPercent: 54,
  },
  zippyCampus: {
    id: "zippy-campus",
    artwork: "logistics",
    category: "Logistics",
    creator: "Chinedu Eze",
    creatorInitials: "CE",
    description:
      "On-demand deliveries connecting students to anything on campus.",
    discoveryCategory: "technology",
    prePledged: { atomic: "160000000", currency: "NGN", decimals: 2 },
    supporters: 76,
    title: "ZippyCampus",
    validationPercent: 45,
  },
  cropCircle: {
    id: "crop-circle",
    artwork: "food",
    category: "Agriculture",
    creator: "Morenike Afolabi",
    creatorInitials: "MA",
    description:
      "Shared equipment bookings that help small farms access tools when they need them.",
    discoveryCategory: "agriculture",
    prePledged: { atomic: "240000000", currency: "NGN", decimals: 2 },
    supporters: 104,
    title: "CropCircle",
    validationPercent: 58,
  },
  agroRoute: {
    id: "agroroute",
    artwork: "logistics",
    category: "Agriculture",
    creator: "Femi Danladi",
    creatorInitials: "FD",
    description:
      "A coordinated produce route connecting rural growers with city retailers.",
    discoveryCategory: "agriculture",
    prePledged: { atomic: "310000000", currency: "NGN", decimals: 2 },
    supporters: 127,
    title: "AgroRoute",
    validationPercent: 63,
  },
  ecoCharge: {
    id: "ecocharge-kiosks",
    artwork: "energy",
    category: "Clean energy",
    creator: "Efe Ighalo",
    creatorInitials: "EI",
    description:
      "Solar charging kiosks for traders and commuters in busy neighbourhood markets.",
    discoveryCategory: "clean-energy",
    prePledged: { atomic: "360000000", currency: "NGN", decimals: 2 },
    supporters: 149,
    title: "EcoCharge Kiosks",
    validationPercent: 64,
  },
  solarChill: {
    id: "solarchill",
    artwork: "energy",
    category: "Clean energy",
    creator: "Yusuf Lawal",
    creatorInitials: "YL",
    description:
      "Modular solar refrigeration for medicine and fresh food in off-grid communities.",
    discoveryCategory: "clean-energy",
    prePledged: { atomic: "420000000", currency: "NGN", decimals: 2 },
    supporters: 171,
    title: "SolarChill",
    validationPercent: 69,
  },
  storyFoundry: {
    id: "story-foundry",
    artwork: "creative",
    category: "Creative",
    creator: "Kelechi Nnamani",
    creatorInitials: "KN",
    description:
      "A collaborative production space for independent African animators and writers.",
    discoveryCategory: "creative",
    prePledged: { atomic: "220000000", currency: "NGN", decimals: 2 },
    supporters: 91,
    title: "StoryFoundry",
    validationPercent: 52,
  },
  skillCircle: {
    id: "skill-circle",
    artwork: "community",
    category: "Community",
    creator: "Ngozi Okafor",
    creatorInitials: "NO",
    description:
      "Neighbourhood skill exchanges that turn spare time into practical local support.",
    discoveryCategory: "community",
    prePledged: { atomic: "145000000", currency: "NGN", decimals: 2 },
    supporters: 83,
    title: "SkillCircle",
    validationPercent: 49,
  },
  careBridge: {
    id: "care-bridge",
    artwork: "community",
    category: "Community",
    creator: "Amina Sadiq",
    creatorInitials: "AS",
    description:
      "A trusted coordination network for family caregivers and community volunteers.",
    discoveryCategory: "community",
    prePledged: { atomic: "175000000", currency: "NGN", decimals: 2 },
    supporters: 96,
    title: "CareBridge",
    validationPercent: 56,
  },
  marketBasket: {
    id: "market-basket",
    artwork: "campus",
    category: "Food & retail",
    creator: "Bola Adekunle",
    creatorInitials: "BA",
    description:
      "Group buying for household staples with transparent local pickup schedules.",
    discoveryCategory: "food-retail",
    prePledged: { atomic: "205000000", currency: "NGN", decimals: 2 },
    supporters: 118,
    title: "MarketBasket",
    validationPercent: 60,
  },
  kitchenCollective: {
    id: "kitchen-collective",
    artwork: "food",
    category: "Food & retail",
    creator: "Tolu Martins",
    creatorInitials: "TM",
    description:
      "Shared certified kitchens helping small food brands produce and sell safely.",
    discoveryCategory: "food-retail",
    prePledged: { atomic: "265000000", currency: "NGN", decimals: 2 },
    supporters: 132,
    title: "Kitchen Collective",
    validationPercent: 62,
  },
} satisfies Record<string, IdeaSummary>;

export const homePreviewData: HomeDashboardData = {
  user: { firstName: "Amara" },
  stats: {
    ideasSupported: 4,
    activePrePledges: 3,
    feedbackResponses: 2,
  },
  featuredIdeas: [
    previewIdeas.campusKonekt,
    previewIdeas.sunGrid,
    previewIdeas.farmLink,
  ],
  prePledges: [
    {
      idea: previewIdeas.campusKonekt,
      intent: { atomic: "5000000", currency: "NGN", decimals: 2 },
      status: "waiting",
    },
    {
      idea: previewIdeas.sunGrid,
      intent: { atomic: "3000000", currency: "NGN", decimals: 2 },
      status: "gathering",
    },
    {
      idea: previewIdeas.farmLink,
      intent: { atomic: "2000000", currency: "NGN", decimals: 2 },
      status: "gathering",
    },
  ],
  discoverIdeas: [
    previewIdeas.studyMate,
    previewIdeas.zippyCampus,
    previewIdeas.cropCircle,
    previewIdeas.agroRoute,
    previewIdeas.ecoCharge,
    previewIdeas.solarChill,
    previewIdeas.naijaCraft,
    previewIdeas.storyFoundry,
    previewIdeas.skillCircle,
    previewIdeas.careBridge,
    previewIdeas.marketBasket,
    previewIdeas.kitchenCollective,
  ],
};
